"""Harvest real instruction/response pairs from the fleet's git history.

Eight training runs established the thing this project keeps relearning: a
0.5B LoRA absorbs *style* reliably and *facts* not at all. Run 6 tripled the
document data and the eval score stayed flat. Run 8 added twelve real
instruction/response pairs hand-picked from this repo's git log and fixed a
regression that more document text could not. So the highest-value training
data is not more docs, it is more instruction/response pairs in Joshua's
actual voice, and there are thousands of them sitting in git history across
~50 repos.

The task harvested here is real and learnable without any model in the loop:
given the files a commit touched, write its subject line. The response is a
genuine commit message Joshua wrote, never invented, so the voice is real by
construction.

Deliberately not harvested: merge commits, dependency bumps, anything
auto-generated, and anything co-authored by an AI. Training a model to
imitate its own prior output is how a voice collapses into an average of
itself.

Usage: ./.venv/bin/python harvest_voice.py [--limit 400] [--out data/voice.md]
"""
import os, re, subprocess, sys

CODE = os.path.expanduser("~/Documents/Code")
REPO = os.path.dirname(os.path.abspath(__file__))

# a subject line that teaches nothing about voice
SKIP = re.compile(
    r"^(?:merge\b|bump\b|update dependenc|chore\(deps|revert\b|wip\b|"
    r"initial commit|v?\d+\.\d+\.\d+$|fix typo$|update readme$)",
    re.I,
)


def repos():
    for name in sorted(os.listdir(CODE)):
        path = os.path.join(CODE, name)
        if os.path.isdir(os.path.join(path, ".git")):
            yield name, path


def commits(path, per_repo):
    """(subject, changed files) for real authored commits, newest first."""
    try:
        out = subprocess.run(
            # trailing %x1f closes the body explicitly, so everything after
            # the third separator is the --name-only file list. Without it a
            # commit body containing slashes (a URL, a session id) parsed as
            # filenames, which produced instructions naming things that were
            # never files.
            ["git", "-C", path, "log", f"-{per_repo}", "--no-merges",
             "--pretty=format:%x1e%H%x1f%s%x1f%b%x1f", "--name-only"],
            capture_output=True, text=True, timeout=30,
        ).stdout
    except Exception:
        return
    for record in out.split("\x1e"):
        record = record.strip("\n")
        if not record:
            continue
        parts = record.split("\x1f")
        if len(parts) < 4:
            continue
        _sha, subject, body, files_blob = parts[0], parts[1], parts[2], parts[3]
        files = [f.strip() for f in files_blob.split("\n")
                 if f.strip() and " " not in f.strip() and "://" not in f
                 and "." in os.path.basename(f.strip())]
        subject = subject.strip()
        if not subject or SKIP.match(subject) or len(subject) < 12 or len(subject) > 120:
            continue
        # never train on text an AI wrote, including this session's own
        if "Co-Authored-By: Claude" in body or "Generated with" in body:
            continue
        if files:
            yield subject, files[:6]


def main():
    limit = 400
    out_path = os.path.join(REPO, "data", "voice.md")
    if "--limit" in sys.argv:
        limit = int(sys.argv[sys.argv.index("--limit") + 1])
    if "--out" in sys.argv:
        out_path = sys.argv[sys.argv.index("--out") + 1]

    pairs, seen = [], set()
    per_repo = max(10, limit // 20)
    for name, path in repos():
        for subject, files in commits(path, per_repo):
            key = subject.lower()
            if key in seen:
                continue
            seen.add(key)
            listing = ", ".join(os.path.basename(f) for f in files)
            pairs.append((
                f"Write a commit message for a change to {listing} in the {name} project.",
                subject,
            ))
            if len(pairs) >= limit:
                break
        if len(pairs) >= limit:
            break

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write("# Harvested voice examples\n\nGenerated by harvest_voice.py "
                "from real commit messages across the fleet. Do not edit by "
                "hand, regenerate instead.\n\n")
        for instruction, response in pairs:
            f.write(f"## {instruction}\n\n{response}\n\n")

    print(f"{len(pairs)} pairs from {len(list(repos()))} repos -> {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
