// Generated by gen_jt_docs.py from the joshuatree repo's README, WHITEPAPER,
// ARCHITECTURE and roadmap. Regenerate after a Joshua Tree docs change:
// python3 gen_jt_docs.py. Do not hand-edit.
export const JT_DOCS = `== Joshua Tree ==
Joshua Tree is an operating system: A desktop built from nothing in C: bootloader, kernel, memory manager, filesystem, network stack, window system, typeface renderer, and 25 native apps. No libc, no external dependencies beyond Clang, lld, and QEMU. Run live in the browser: joshuatree.heyitsmejosh.com It also runs live in a browser tab at joshuatree.heyitsmejosh.com, the same kernel, not a recording. Joshua Trommel is building it, and why: Every computer I have ever used was someone else's decisions, stacked a thousand deep, none of which I could see. I wanted one machine where I understand the whole thing. Not "trust the abstraction." Actually know why that bit is set in that page table. The longer goal is a computer I built end to end: this software, on hardware I solder myself, talking to a language model I trained, with no cloud in the loop. This is the software half. It is licensed Apache License 2.0, copyright 2026 Joshua Trommel, free and open source, code on GitHub at github.com/nulljosh/joshuatree.

== Version and booting it ==
The current version of Joshua Tree is 1.0.3. Versions follow semver (major.minor.patch): minor for a new capability, patch for a fix. Try it live in a browser at joshuatree.heyitsmejosh.com, no install. To run it as the real OS on a PC, write the ISO from GitHub Releases to a USB stick and boot from it. Joshua Tree is a kernel for a 32-bit Intel (i386) machine, written from nothing: its own bootloader, memory manager, filesystem, network stack, window system and typeface renderer, no Linux or any other OS underneath it.

== Apps and the dock ==
All 25 apps live in the Apps folder; the dock pins a handful of them: the Apps folder, Files, Mail, Calendar, Notes, Reminders, Terminal, Chat, Weather, Stocks, Trash.
Files: Files browses the real filesystem (FAT16 on a real disk, or a small RAM disk in the browser demo), the Finder equivalent.
Mail: MAIL.TXT, \\|-delimited from\\|subject\\|body\\|read.
Calendar: No file for the grid itself, today's date comes straight from the RTC's CMOS BCD registers each time; day-of-week is Zeller's congruence, swept against libc's own timegm for every.
Notes: NOTES.TXT, a single 4095-byte buffer.
Reminders: REMINDERS.TXT, one line per item: 0/1 done flag, a space, the text.
Terminal: Terminal is the same shell the machine boots into, just running in a window.
Chat: CHAT.TXT, role\\|content per line, an 8-message bounded ring (oldest drops once full).
Weather: Weather pulls a live forecast from Open-Meteo by IP geolocation, shown in the menu bar and in its own app.
Curbfind: Craigslist deal rankings for Vancouver, native: left side shows ranked list (1-10 sample listings) sorted by deal score descending, selected row highlighted, price right-aligned.
Keyrate: Keyrate is a real native typing test: a word list, a live input loop, your words-per-minute.
Bookrank: curated non-fiction rankings, native: left side shows ranked list (1-10) with selected row highlighted, up/down or click to select; right side shows title, author and 2-3 sentence.
Quotes: Quotestreak native: a film line, four titles, 1-4 or a click answers, streak and best kept for the session.
Plan: Joshua's ten-year education and career roadmap, native: left side shows milestone timeline with selected row highlighted, up/down or click to select; right side shows "The next.
Lexly: Spanish vocabulary drill: a word in Spanish, four English choices, 1-4 or a click answers, streak and best kept for the session.
Toroid: Conway's Game of Life on a torus, native: both edges wrap, space pauses, r reseeds, c clears, a click toggles a cell.
Sparkjar: a jar of ideas people post and vote on, native: left side shows list (1-10 ideas) sorted by votes descending, selected row highlighted, vote count displayed right-aligned in each.
Homeqi: Feng shui home assessment condensed from Eva Wong's Good Fengshui, native: eight yes/no questions about your home (front door, natural light, bed position, clutter, water, power.
Fieldbook: every field of science and math explained plainly, native: left side shows ranked list (1-12) with selected row highlighted, up/down or click to select; right side shows field.
Contacts: CONTACTS.TXT, same VFS write-through shape as the other three: a fixed-size static array (name/phone/email), view/add/delete.
Calculator: doesn't fit the VFS-backed table above, it has no persistence at all on purpose: a recursive-descent parser over + - / () and numbers, one-line input evaluated on enter.
Stocks: is the basic native one, shaped like macOS Stocks: a scrolling watchlist sidebar (sparkline, price, colored change pill) beside a detail pane with 1D/1W/1M/3M/1Y range tabs, a.
Search: Apps-folder-only like Contacts/ Calculator/Stocks, no persistence of its own since it mirrors the real filesystem rather than owning a file.
Epiphany: is our own, richer take, a deliberately separate app from Stocks: the offline slice of github.com/nulljosh/epiphany.
Portfolio: Apps-folder-only like Search/Contacts/Calculator/Stocks.
Activity: Apps-folder-only like Search (icon 24; Apps folder/Trash at 25/26, after Portfolio took 23), a real Activity Monitor-shaped window over the exact primitives the shell's own.

== Accounts and Lock Screen ==
Settings has an Add user step: an account's password is salted and hashed, never stored in the clear. Once an account exists, booting shows a real login screen; a wrong password is rejected with a short delay. The tree-logo Apple menu in the top corner has Lock Screen: with an account, it re-locks the machine the same way a reboot's login screen does; with no account yet, it just shows a brief message. The same menu also has About, Files, Notes, Settings, Restart and Shut Down.

== What it does not do ==
Joshua Tree has no Wi-Fi and no Bluetooth; it only has wired networking. Decided for 1.0, stated in the release notes: no Wi-Fi, no Bluetooth (both need firmware blobs and a full 802.11 or BT stack, months of work each), English only (every UI string is compiled in; a language table is a 1.1 project), no screen reader (no sound yet). Keyboard-only use and large text in Notes are the accessibility floor. There is no cloud in the loop: the Chat app talks to a local language model over this kernel's own network stack, plain HTTP, no TLS built yet.`;
